import = [
  "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 10.0

[window]
# decorations = "None"
# startup_mode = "Maximized" # currently broken in GNOME
padding.x = 10
padding.y = 10
