import = [
  "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 10.0

[window]
decorations = "None"
startup_mode = "Maximized"
padding.x = 5
padding.y = 5
